src/Entity/Trajet.php
<?php

namespace App\Entity;

use App\Repository\TrajetRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TrajetRepository::class)
 */
class Trajet
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville_depart;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville_destination;

    /**
     * @ORM\Column(type="datetime", nullable = true)
     */
    private $date_depart;

    /**
     * @ORM\Column(type="datetime", nullable = true)
     */
    private $date_arrivee;

    /**
     * @ORM\Column(type="integer")
     */
    private $nombre_places;

    /**
     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="trajet")
     */
    private $reservations;

    /**
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="trajet")
     */
    private $commentaires;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="trajets")
     */
    private $conducteur;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getVilleDepart(): ?string
    {
        return $this->ville_depart;
    }

    public function setVilleDepart(string $ville_depart): self
    {
        $this->ville_depart = $ville_depart;

        return $this;
    }

    public function getVilleDestination(): ?string
    {
        return $this->ville_destination;
    }

    public function setVilleDestination(string $ville_destination): self
    {
        $this->ville_destination = $ville_destination;

        return $this;
    }

    public function getDateDepart(): ?\DateTimeInterface
    {
        return $this->date_depart;
    }

    public function setDateDepart(\DateTimeInterface $date_depart): self
    {
        $this->date_depart = $date_depart;

        return $this;
    }

    public function getDateArrivee(): ?\DateTimeInterface
    {
        return $this->date_arrivee;
    }

    public function setDateArrivee(\DateTimeInterface $date_arrivee): self
    {
        $this->date_arrivee = $date_arrivee;

        return $this;
    }

    public function getNombrePlaces(): ?int
    {
        return $this->nombre_places;
    }

    public function setNombrePlaces(int $nombre_places): self
    {
        $this->nombre_places = $nombre_places;

        return $this;
    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setTrajet($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getTrajet() === $this) {
                $reservation->setTrajet(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setTrajet($this);
        }
        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getTrajet() === $this) {
                $commentaire->setTrajet(null);
            }
        }

        return $this;
    }

    public function getConducteur(): ?User
    {
        return $this->conducteur;
    }

    public function setConducteur(?User $conducteur): self
    {
        $this->conducteur = $conducteur;

        return $this;
    }





}

templates/profile/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil de {{ user.prenom }} {{ user.nom }}{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/profile.css') }}">
{% endblock %}
{% block body %}
    <h1>Profil de {{ user.prenom }} {{ user.nom }}</h1>

    <table class="table">
        <tr>
            <th>{% trans %}Email{% endtrans %}</th>
            <td>{{ user.email }}</td>
        </tr>
        <tr>
            <th>{% trans %}Téléphone{% endtrans %}</th>
            <td>{{ user.telephone }}</td>
        </tr>
        <tr>
            <th>{% trans %}Nombre de trajets{% endtrans %}</th>
            <td>{{ user.trajets|length }}</td>
        </tr>
        <tr>
            <th>{% trans %}Nombre de réservations{% endtrans %}</th>
            <td>{{ user.reservations|length }}</td>
        </tr>
        <tr>
            <th>{% trans %}Nombre de commentaires{% endtrans %}</th>
            <td>{{ user.commentaires|length }}</td>
        </tr>
        <tr>
            <th>{% trans %}Notes reçues{% endtrans %}</th>
            <td>{{ user.getNotesRecues()|length }}</td>
        </tr>
    </table>

    <h1>{% trans %}Mes trajets proposés{% endtrans %}</h1>
    {% if user.trajets|length > 0 %}
        <ul>
            {% for trajet in user.trajets %}
                <a href="{{ path('trajet.show', {id: trajet.id}) }}" class="trajet-link">
                    <div class="trajet-card">
                        <div class="trajet-locations">
                            <div class="trajet-location-depart">
                                <p>{{ trajet.villeDepart }}</p>
                            </div>
                            <div class="trajet-location-destination">
                                <p>{{ trajet.villeDestination }}</p>
                            </div>
                        </div>
                        <div class="trajet-details">
                            <div class="trajet-dates">
                                <p>{% trans %}Départ{% endtrans %} : {{ trajet.dateDepart|date('d/m/Y H:i') }}</p>
                                <p>{% trans %}Arrivée{% endtrans %} : {{ trajet.dateArrivee|date('d/m/Y H:i') }}</p>
                            </div>
                            <div class="trajet-places">
                                <p>{{ trajet.nombrePlaces }} {% trans %}places disponibles{% endtrans %}</p>
                            </div>
                            <a href="{{ path('trajet.edit', {id: trajet.id}) }}" class="editer"> {% trans %}Editer{% endtrans %}</a>
                            <a href="{{ path('trajet.delete', {id: trajet.id}) }}" class="supprimer">{% trans %}Supprimer{% endtrans %}</a>
                        </div>
                    </div>
                </a>
            {% endfor %}

        </ul>
    {% else %}
        <p>{% trans %}Aucun trajet proposé pour le moment{% endtrans %}.</p>
    {% endif %}

        <h1>{% trans %}Mes notes reçues{% endtrans %}</h1>
    <div class = "notes_recues">
        {% if user.getNotesRecues()|length > 0 %}
            <ul>
                {% for note in user.getNotesRecues() %}
                    <li>{{ note.passager.prenom }} {{ note.passager.nom }} : {{ note.valeur }} / 5 - {{ note.commentaire }}</li>
                {% endfor %}
            </ul>
        {% else %}
            <p>{% trans %}Aucune note reçue pour le moment.{% endtrans %}</p>
        {% endif %}
    </div>
{% endblock %}