src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReservationRepository::class)
 */
class Reservation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="reservations")
     * @ORM\JoinColumn(nullable=true)
     */
    private $passager;

    /**
     * @ORM\ManyToOne(targetEntity=Trajet::class, inversedBy="reservations")
     * @ORM\JoinColumn(nullable=true)
     */
    private $trajet;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPassager(): ?User
    {
        return $this->passager;
    }

    public function setPassager(?User $passager): self
    {
        $this->passager = $passager;

        return $this;
    }

    public function getTrajet(): ?Trajet
    {
        return $this->trajet;
    }

    public function setTrajet(?Trajet $trajet): self
    {
        $this->trajet = $trajet;

        return $this;
    }

}

src/Entity/Trajet.php
<?php

namespace App\Entity;

use App\Repository\TrajetRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TrajetRepository::class)
 */
class Trajet
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville_depart;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville_destination;

    /**
     * @ORM\Column(type="datetime", nullable = true)
     */
    private $date_depart;

    /**
     * @ORM\Column(type="datetime", nullable = true)
     */
    private $date_arrivee;

    /**
     * @ORM\Column(type="integer")
     */
    private $nombre_places;

    /**
     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="trajet")
     */
    private $reservations;

    /**
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="trajet")
     */
    private $commentaires;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="trajets")
     */
    private $conducteur;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getVilleDepart(): ?string
    {
        return $this->ville_depart;
    }

    public function setVilleDepart(string $ville_depart): self
    {
        $this->ville_depart = $ville_depart;

        return $this;
    }

    public function getVilleDestination(): ?string
    {
        return $this->ville_destination;
    }

    public function setVilleDestination(string $ville_destination): self
    {
        $this->ville_destination = $ville_destination;

        return $this;
    }

    public function getDateDepart(): ?\DateTimeInterface
    {
        return $this->date_depart;
    }

    public function setDateDepart(\DateTimeInterface $date_depart): self
    {
        $this->date_depart = $date_depart;

        return $this;
    }

    public function getDateArrivee(): ?\DateTimeInterface
    {
        return $this->date_arrivee;
    }

    public function setDateArrivee(\DateTimeInterface $date_arrivee): self
    {
        $this->date_arrivee = $date_arrivee;

        return $this;
    }

    public function getNombrePlaces(): ?int
    {
        return $this->nombre_places;
    }

    public function setNombrePlaces(int $nombre_places): self
    {
        $this->nombre_places = $nombre_places;

        return $this;
    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setTrajet($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getTrajet() === $this) {
                $reservation->setTrajet(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setTrajet($this);
        }
        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getTrajet() === $this) {
                $commentaire->setTrajet(null);
            }
        }

        return $this;
    }

    public function getConducteur(): ?User
    {
        return $this->conducteur;
    }

    public function setConducteur(?User $conducteur): self
    {
        $this->conducteur = $conducteur;

        return $this;
    }





}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique = true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, unique = true)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $mot_de_passe;

    /**
     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="passager")
     */
    private $reservations;

    /**
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="user")
     */
    private $commentaires;

    /**
     * @ORM\OneToMany(targetEntity=Note::class, mappedBy="passager")
     */
    private $notes_donnees;

    /**
     * @ORM\OneToMany(targetEntity=Note::class, mappedBy="conducteur")
     */
    private $notes_recues;

    /**
     * @ORM\OneToMany(targetEntity=Trajet::class, mappedBy="conducteur")
     */
    private $trajets;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
        $this->notes_donnees = new ArrayCollection();
        $this->notes_recues = new ArrayCollection();
        $this->trajets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getMotDePasse(): ?string
    {
        return $this->mot_de_passe;
    }

    public function setMotDePasse(string $mot_de_passe): self
    {
        $this->mot_de_passe = $mot_de_passe;

        return $this;
    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setPassager($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getPassager() === $this) {
                $reservation->setPassager(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setUser($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getUser() === $this) {
                $commentaire->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Note>
     */
    public function getNotesDonnees(): Collection
    {
        return $this->notes_donnees;
    }

    public function addNotesDonnee(Note $notesDonnee): self
    {
        if (!$this->notes_donnees->contains($notesDonnee)) {
            $this->notes_donnees[] = $notesDonnee;
            $notesDonnee->setPassager($this);
        }

        return $this;
    }

    public function removeNotesDonnee(Note $notesDonnee): self
    {
        if ($this->notes_donnees->removeElement($notesDonnee)) {
            // set the owning side to null (unless already changed)
            if ($notesDonnee->getPassager() === $this) {
                $notesDonnee->setPassager(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Note>
     */
    public function getNotesRecues(): Collection
    {
        return $this->notes_recues;
    }

    public function addNotesRecue(Note $notesRecue): self
    {
        if (!$this->notes_recues->contains($notesRecue)) {
            $this->notes_recues[] = $notesRecue;
            $notesRecue->setConducteur($this);
        }

        return $this;
    }

    public function removeNotesRecue(Note $notesRecue): self
    {
        if ($this->notes_recues->removeElement($notesRecue)) {
            // set the owning side to null (unless already changed)
            if ($notesRecue->getConducteur() === $this) {
                $notesRecue->setConducteur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Trajet>
     */
    public function getTrajets(): Collection
    {
        return $this->trajets;
    }

    public function addTrajet(Trajet $trajet): self
    {
        if (!$this->trajets->contains($trajet)) {
            $this->trajets[] = $trajet;
            $trajet->setConducteur($this);
        }

        return $this;
    }

    public function removeTrajet(Trajet $trajet): self
    {
        if ($this->trajets->removeElement($trajet)) {
            // set the owning side to null (unless already changed)
            if ($trajet->getConducteur() === $this) {
                $trajet->setConducteur(null);
            }
        }

        return $this;
    }


    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return $this->mot_de_passe;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    public function getUsername()
    {
        return $this->email;
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }
    public function getNoteMoyenne(): float
    {
        $totalNotes = 0;
        $nbNotes = count($this->notes_recues);

        if ($nbNotes === 0) {
            return 0;
        }

        foreach ($this->notes_recues as $note) {
            $totalNotes += $note->getValeur();
        }

        return round($totalNotes / $nbNotes, 1);
    }

}

templates/reservation/delete.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Supprimer une réservation{% endtrans %}{% endblock %}
        {% block stylesheets %}
            {{ parent() }}
            <link rel="stylesheet" href="{{ asset('css/deleteTrajet.css') }}">
        {% endblock %}
{% block body %}
    <h1>{% trans %}Supprimer la réservation{% endtrans %}</h1>
    <p>
        {% trans %}Êtes-vous sûr de vouloir supprimer la réservation pour le trajet{% endtrans %} {{ reservation.trajet.getVilleDepart() }} --> {{ reservation.trajet.getVilleDestination() }} ?
    </p>

    {{ form_start(form) }}
    {{ form_widget(form.submit, { 'attr': {'class': 'btn btn-danger'} }) }}
    <a href="{{ path('reservation.show', { 'id': reservation.id }) }}" class="btn btn-secondary">{% trans %}Annuler{% endtrans %}</a>
    {{ form_end(form) }}
{% endblock %}

templates/reservation/history.html.twig
{% extends 'base.html.twig' %}
{% block title %}Historique des réservations{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/reservation-history.css') }}">
{% endblock %}
{% block body %}

    {% for message_type, messages in app.flashes %}
        {% for message in messages %}
            <div class="alert alert-{{ message_type }} alert-dismissible fade show" role="alert">
                {{ message|trans }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endfor %}
    <div class="container">
        <h1>{% trans %}Historique des réservations{% endtrans %}</h1>
        <table class="table">
            <thead>
            <tr>
                <th>{% trans %}Trajet{% endtrans %}</th>
                <th>{% trans %}Date de départ{% endtrans %}</th>
                <th>{% trans %}Date d'arrivée{% endtrans %}</th>
                <th>{% trans %}Conducteur{% endtrans %}</th>
            </tr>
            </thead>
            <tbody>
            {% for reservation in reservations %}
            <tr>
                <td>{{ reservation.trajet.villeDepart }} → {{ reservation.trajet.villeDestination }}</td>
                <td>{{ reservation.trajet.getDateDepart()|date('d/m/Y H:i') }}</td>
                <td>{{ reservation.trajet.getDateArrivee()|date('d/m/Y H:i') }}</td>
                <td>{{ reservation.trajet.conducteur.prenom }} {{ reservation.trajet.conducteur.nom }}</td>
                <td>
                    <form action="{{ path('note_add', {'trajetId': reservation.trajet.id}) }}" method="POST">
                        <label for="valeur-{{ reservation.trajet.id }}">{% trans %}Note{% endtrans %} :</label>
                        <select name="valeur" id="valeur-{{ reservation.trajet.id }}" required>
                            <option value="">{% trans %}Sélectionnez une note{% endtrans %}</option>
                            {% for i in 1..5 %}
                            <option value="{{ i }}">{{ i }}</option>
                            {% endfor %}
                        </select>
                        <label for="commentaire-{{ reservation.trajet.id }}">{% trans %}Commentaire{% endtrans %} :</label>
                        <textarea name="commentaire" id="commentaire-{{ reservation.trajet.id }}" rows="3" placeholder="Votre commentaire..."></textarea>
                        <button type="submit" class="btn btn-primary">{% trans %}Ajouter une note{% endtrans %}</button>
                    </form>
                </td>
            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
{% endblock %}

templates/reservation/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Liste des réservations{% endtrans %}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/reservation-list.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
{% endblock %}

{% block body %}
    <div class="container">
        <h1>{% trans %}Liste des réservations{% endtrans %}</h1>

        <div class="mb-3">
            <a href="{{ path('reservation.history') }}" class="btn btn-secondary">{% trans %}Voir l'historique des réservations{% endtrans %}</a>
        </div>

        {% set isAdmin = 'ROLE_ADMIN' in app.user.roles %}

        <div class="reservation-list">
            {% for reservation in reservations %}
                {% if isAdmin or app.user == reservation.passager %}
                    <div class="reservation-card">
                        <div class="reservation-info">
                            {% if isAdmin %}
                                <div class="reservation-passenger">
                                    {% trans %}Passager{% endtrans %}: {{ reservation.passager.username }}
                                </div>
                            {% endif %}
                            <div class="reservation-location">
                                {{ reservation.trajet.getVilleDepart() }} &#x2192; {{ reservation.trajet.getVilleDestination() }}
                            </div>
                            <div class="reservation-dates">
                                <p>{% trans %}Départ{% endtrans %} : {{ reservation.trajet.getDateDepart()|date('d/m/Y H:i') }}</p>
                                <p>{% trans %}Arrivée{% endtrans %} : {{ reservation.trajet.getDateArrivee()|date('d/m/Y H:i') }}</p>
                            </div>
                        </div>
                        <div class="reservation-actions">
                            <a href="{{ path('reservation.show', {'id': reservation.id}) }}" class="btn btn-info">{% trans %}Détails{% endtrans %}</a>
                            {% if app.user == reservation.passager or isAdmin %}
                                <a href="{{ path('reservation.delete', {'id': reservation.id}) }}" class="btn btn-danger">{% trans %}Supprimer{% endtrans %}</a>
                                <a href="{{ path('add_comment', {'reservationId': reservation.id}) }}" class="btn btn-primary">
                                    {% trans %}Ajouter un commentaire{% endtrans %}
                                </a>
                            {% endif %}
                        </div>
                    </div>
                {% endif %}
            {% else %}
                <div class="no-reservations-found">
                    {% trans %}Aucune réservation trouvée.{% endtrans %}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/reservation/show.html.twig
{# templates/reservation/show.html.twig #}

{% extends 'base.html.twig' %}

{% block title %}{% trans %}Détails de la réservation{% endtrans %}{% endblock %}
        {% block stylesheets %}
            {{ parent() }}
            <link rel="stylesheet" href="{{ asset('css/reservation.css') }}">
        {% endblock %}
{% block body %}
    <h1>{% trans %}Détails de la réservation{% endtrans %}</h1>

    <table class="table">
        <tr>
            <th>{% trans %}Passager{% endtrans %}</th>
            <td>{{ reservation.passager.username }}</td>
        </tr>
        <tr>
            <th>{% trans %}Ville de départ{% endtrans %}</th>
            <td>{{ reservation.trajet.getVilleDepart() }}</td>
        </tr>
        <tr>
            <th>{% trans %}Ville de destination{% endtrans %}</th>
            <td>{{ reservation.trajet.getVilleDestination() }}</td>
        </tr>
        <tr>
            <th>{% trans %}Date de départ{% endtrans %}</th>
            <td>{{ reservation.trajet.getDateDepart()|date('d/m/Y H:i') }}</td>
        </tr>
        <tr>
            <th>{% trans %}Date d'arrivée{% endtrans %}</th>
            <td>{{ reservation.trajet.getDateArrivee()|date('d/m/Y H:i') }}</td>
        </tr>
        <tr>
            <th>{% trans %}Nombre de places{% endtrans %}</th>
            <td>{{ reservation.trajet.getNombrePlaces() }}</td>
        </tr>
    </table>

    <a href="{{ path('reservation.list') }}" class="btn btn-primary">{% trans %}Retour à la liste des réservations{% endtrans %}</a>
    {% if app.user == reservation.passager or 'ROLE_ADMIN' in app.user.roles %}
        <a href="{{ path('reservation.delete', {'id': reservation.id}) }}" class="btn btn-danger">{% trans %}Supprimer{% endtrans %}</a>
    {% endif %}
{% endblock %}